$L2:
if(a != 0)	goto $L3
$t0	=	1	+	4
s	=	$t0
		goto $L1
$L3:
if(a != 1)	goto $L4
a	=	b
$t1	=	b	+	2
$L6:
if($t1 != 2)	goto $L7
$t2	=	b	+	c
d	=	$t2
		goto $L5
$L7:
if($t1 != 3)	goto $L8
		goto $L9
$L8:
if($t1 != 4)	goto $L10
$L9:
c	=	r
		goto $L5
$L10:
$L5:
		goto $L11
$L4:
if(a != 2)	goto $L12
$L11:
s	=	2
		goto $L1
$L12:
if(a != 3)	goto $L13
s	=	3
		goto $L1
$L13:
if(a != 4)	goto $L14
s	=	7
		goto $L15
$L14:
if(a != 5)	goto $L16
$L15:
s	=	9
		goto $L1
$L16:
p	=	q
		goto $L1
$L17:
$L1:
$L18:
$t2	=	b	*	c
$t3	=	a	+	$t2
if( not $t3)	goto $L19
$t1	=	a	>	b
	if( not $t1)	goto $L20
a	=	b
		goto $L21
$L20: 
c	=	d
$L21: 
$t7	=	p	*	q
$t1	=	a	+	b
$t2	=	c	*	$t1
$t3	=	$t7	+	$t2
d	=	$t3
q	=	r
		goto $L18
$L19: 
